package com.example.dynamo.models;

import com.amazonaws.services.dynamodbv2.datamodeling.*;
import com.example.dynamo.documents.Retailer;

@DynamoDBTable(tableName = "ProductInfo")
public class ProductInfo {
    private String id;
    private String msrp;
    private String cost;
    private Retailer retailer;

    public ProductInfo(String id, String msrp, String cost) {
        this.id = id;
        this.msrp = msrp;
        this.cost = cost;
    }

    public ProductInfo() {
    }

    @DynamoDBHashKey
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }
    public void setId(String id) {
        this.id = id;
    }

    @DynamoDBAttribute
    public String getMsrp() {
        return msrp;
    }
    public void setMsrp(String msrp) {
        this.msrp = msrp;
    }

    @DynamoDBAttribute
    public String getCost() {
        return cost;
    }
    public void setCost(String cost) {
        this.cost = cost;
    }

    @DynamoDBAttribute(attributeName="retailer")
    public Retailer getRetailer() { return retailer;}
    public void setRetailer(Retailer retailer) {this.retailer = retailer;}



}